services:
  - type: web
    name: lipin-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.16
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/ms-playwright
